-- AlterTable
ALTER TABLE "Radio" ADD COLUMN "fistMic" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Radio" ADD COLUMN "surveillance" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Radio" ADD COLUMN "doubleMuff" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Radio" ADD COLUMN "lightweight" BOOLEAN NOT NULL DEFAULT false;
